# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b67920ae3869da0479bc17b77d80c3d9af89e8d3d214f22970fcecdb9560c9387f9e4eb9ca82867d5bd0862863ca82ab4825190d7e6251cd1d8687ada5885ab9

test:
  secret_key_base: b74b5d3b43ff49198e4544ded61e18a85023377c3eb5a068dec2c7cf464b7d2eb13c132815e2d111b7da6c755cdd9bfbd06be0a68c136aa2f9329aa8e7eebed9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
